language: python

python: '3.6'

install: make init

script: make build_deploy

env:
  global:
  - ENCRYPTION_LABEL: 2dbed6352b90
  - COMMIT_AUTHOR_EMAIL: "cloud4rpi@gmail.com"


notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: OuoX9d5Cztvl7vimVrtAh/N0PQ0+x+y8s84cY6E0vei6ArIBlrcNJe1tftQW6a88RXi0VKbpFC8toTMCuz9FJHWlAy9YdaonsLF/06tXng9U3Ihj35VZ30MHTNpSsdbRx6DzzPYFHOjIzqCbFyYQZqKT6hEsk/v0fOCrM4tmtkIvuZcsmMDBg8WZCx53LDkUHx48RSHpqI699m0C1NMoaYTe+v9bmWkShVd8rFGiD20VH8aCVwddEaosqsm4wfCK38s+3jkYwF2ptoLLzrHSE5nQZIVRo5sg4euZCch9+I8+LG1Wzol2k6haWM4lhf+ia0Re4+rxee+FehqKCj4E4TexvaKSEG8pfSNJwJuP6krBesfZ3rmMSK1uTMQZdHwX8hIalzQjCnmxO1dR1Iu2WAtZ0wl7JOWkWh5vaxixwdK79jt/AZXCbZ9HvaGMlpDlisW0yn1Ob0YfqX1xZ6FZhC76qtFgzIJLgCd4ctTFCoo+Ks8EP1A9bKl6DkjmCM/19v+d2UGs6iax7KOzL4BAZxGfYDAIZdi3XAQDgf5+KUZV/82EqifYI2OH8LXHi4eiFB3RKgEVG33rzPg8rBZLAoJNlScvE78/urRDaBywZxiABj3VOQQ9VqBiaRrJt63ioTVRywJMhByKC/gLWG75xRIEGeXvMo0bEAkQWyrG3rA=
